sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn test:coverage
- yarn test:coveralls
after_success:
- yarn build
deploy:
  provider: heroku
  app: b2b-pokemon-react
  api_key:
    secure: Qi+OT3TPxuG+RV23YSg5ZXW3w834jj4mE5GlI36kySjgSxyLnu/kRJooAm1gdHwFtkIyABaRMSMRKiM28fjU9t2rqpR0nngrPGXH9/93Xyga7LZRfxMTeFTQfm1Kcr483axTmL6R+VSoQHyCOB/LOZF+I+Z4h9noyYWj2qJtWlbBCeoinm8UiqAlX9mFdgTeSbdDQW6JFZIY3pPvPMdO5ZGOPWfDSHP7Ry3rr38WfsqhiBTJxSknAs98MFAoG/DNb9v835ttdIpaehri7xM5Dpghmo7VBA9TQXrsyGJuxdRAYlwCy/l4MeMRCtYlloHj1F13y9q+/CANlPv2c9GmLbOoKv0m7NBY5EWrTifsDZ+GXtT9ucCIeTC6XAfLz5elyAtDWP5huE2MMPp8/gfNUoLVQtmrfJ4WnU5F9EbAdNX7P4CknRqBSg59Z5zX1ffuj90ys9/dDLcXYOoz/Y+unHpRRvA8w/LJshSVyijZD2OYpFRWTM/t/AtF5VPF0NjHtsnMpGxvRwjbp5IWc9DS2YN96/xcKmlapWkvU5YgzH+xinY5G1BNTVx/Mrg6MTnaAekkdks7O1FLlSNG9aDxkfJsmaJi6OVlq9oa8rDbp5a9xBdLwepVSoczNX2wQucDCVYdMOAkYj0QC/tsq/Xf51r9elyBz38ErAuJRAQHde0=
