sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn test:coverage
- yarn test:coveralls
after_success:
- yarn build
deploy:
  provider: heroku
  app: b2b-pokemon-react
  api_key:
    secure: mavyt2npL9TpAltqUy4EcvMHFypOZC6fm88Gor8Kqw1xKCGN2WwqEvugCrJ9iaLjxC7jBqdsFaPRVfRxzNiBP5hrkY7zsiuOjdldxiiWNGPkARFM5iWIFfZ5phIt66DZJp2klbe9LNkZVV5GFru7GhcyQTlrThDUIfCGHAZRrKXF332uGX/7NqM/7L/Vj2dDue5EGFhP7oJbPCD5j15OttDB/lXwSFsxzwRuhGolpKA1Dk8aHiA/sfpvzTqAcl3Rg4AUF8mYCwbYVz/XXojqw2g7f7C6dBo9ul+7Y8Geb3SU2xwfVmTPgYQWvvlVC058kD7rmd0ITjaEhEsiL5KN7X3APprrmZyK9P3Gx9vPPABfN2C64xVMdVssMP7KB5z/XdFYAJB6wSSrXRoQPTOLUmHtVy/HS2aBQhrdUfKcK+cXUwKpQd8JdYrqr26yItqJ8sXxYQkw/L2DrUu35LZknTLcn8Baf6z8n2wBrne1kg4/3QrXVaWIeN2OFEQOQzHu5CuuTISBX3VRPSS/C18x/3s1mEf63mTePqPFgJef9zxJVvM1BQQifNMAM7d2rGG8qmHTFtnDjExr1PGwItpKdDvZkYwMCiQMwSL4RnEwFUsUEQUAMdm2AHjvwiQ6O9zxpb7jy/UJ5A8zyUX1j3wpDv3AFgarFgghTl/xZihnNFo=
