sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn test:coverage
- yarn test:coveralls
after_success:
- yarn build
deploy:
  provider: heroku
  app: b2b-pokemon-react
  api_key:
    secure: OvSr2ipywVzLtOkIBLLGczY0V6vD5CDPfMX6t68xox+2pFoCYR/w5T8lyTdxp+JxXAHzpwVP8hDGnFhrz7KrbJGnYAE64bTV7QwVcpbdE0BCP66b1g4P5yBgBPCUJ9oPuKdRM3YMq+H6GAVD6bwFfOHIwow0tbcBl1f+4rNwM7BzWw1sXUwwjw2KV9KtG5+kDWZEcxUqAtLQrV0srYfVVnGVCNeE2DOCo6ucwWXvTtUzIxO8fkVQGbnKshoRUQuMpEbFpy7ffVpC9Bn/X4ltZYr0d/KkHRAcHmtuMoDS1FJR7wjyqvMBxQam749+liDQmufc5ogKEPNxN0AZEW04RBn7xqdkNg/ljR+dV6/2QQu5frBQvx/N3rguydFYPjK3IlfOh/0A6bAHpjDSfw3FbzRrFjSVvtSkEE+wVLi8FCpBTSVIO6S0OuooFpnS3w/pRURe4LwhlTe3yqlR2d7vMx0SnOgPXfzonaZ3jLlNEYQhVwBdBy4dgtyLXvHUF6jndeSbpL9XxwZRm1k2ceddtomOq7BLtyRviQZllxicmfGvsvOXvuPGdKbLQ6oKLeaeXv9BDo8X6eMVNbByyfUSd7mP8pWW2QT8PnIzR2xyxo54DOrJtvLZ5ELMm2Na4RaOlmIlSpJyI43rqLqA1Sb39mdMWauWVTgBuhleA9SINqA=
